CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name VARCHAR(25),
  email VARCHAR(50) UNIQUE,
  telephone VARCHAR(10),
  password VARCHAR(60),
  role VARCHAR(10),
  is_admin BOOL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE category (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50)
);

CREATE TABLE products (
  product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_category_id INT,
  name VARCHAR(50),
  price INT,
  description VARCHAR(255),
  img VARCHAR(255),
  available BOOL DEFAULT TRUE,
  quantity INT,
  FOREIGN KEY (fk_category_id) REFERENCES category(category_id)
);

CREATE TABLE orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_user_id INT,
  amount INT,
  created_at TIMESTAMP DEFAULT now(),
  FOREIGN KEY (fk_user_id) REFERENCES users(user_id)
);

CREATE TABLE order_items (
  order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_order_id INT,
  products JSONB,
  FOREIGN KEY (fk_order_id) REFERENCES orders(order_id)
);
